asylum-spm: !include 'applications/asylum-spm.yml'
deepmd: !include 'applications/deepmd.yml'
espresso: !include 'applications/espresso.yml'
lammps: !include 'applications/lammps.yml'
nwchem: !include 'applications/nwchem.yml'
python: !include 'applications/python.yml'
probe-station: !include 'applications/probe-station.yml'
shell: !include 'applications/shell.yml'
vasp: !include 'applications/vasp.yml'
xrf-mapper: !include 'applications/xrf-mapper.yml'
