deepmd: !include 'applications/deepmd.yml'
espresso: !include 'applications/espresso.yml'
lammps: !include 'applications/lammps.yml'
nwchem: !include 'applications/nwchem.yml'
python: !include 'applications/python.yml'
q3: !include 'applications/q3.yml'
shell: !include 'applications/shell.yml'
vasp: !include 'applications/vasp.yml'
